FROM arm32v7/node:8

#RUN groupadd -r signalk && useradd --no-log-init -r -g signalk signalk
#WORKDIR /home/signalk
#RUN chown -R signalk /home/signalk
#USER signalk

COPY package*.json ./
RUN npm install --only=production

COPY . .

EXPOSE 3000
ENTRYPOINT bin/signalk-server
